// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmT8saM9YDlOyOVZ1jF3MxKFib9A-_0-I',
    appId: '1:104906781780:android:9200165030f193755c69c1',
    messagingSenderId: '104906781780',
    projectId: 'flutter-audio-fc1ba',
    databaseURL: 'https://flutter-audio-fc1ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-audio-fc1ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8dFtRyggLuzy9dc3wbM3f2H6hpOZg2Y',
    appId: '1:104906781780:ios:07ceeea16db579155c69c1',
    messagingSenderId: '104906781780',
    projectId: 'flutter-audio-fc1ba',
    databaseURL: 'https://flutter-audio-fc1ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-audio-fc1ba.appspot.com',
    iosClientId:
        '104906781780-jngju1s1e3mg3pk7e4eftt3vm3ra4j9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB8dFtRyggLuzy9dc3wbM3f2H6hpOZg2Y',
    appId: '1:104906781780:ios:07ceeea16db579155c69c1',
    messagingSenderId: '104906781780',
    projectId: 'flutter-audio-fc1ba',
    databaseURL: 'https://flutter-audio-fc1ba-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-audio-fc1ba.appspot.com',
    iosClientId:
        '104906781780-jngju1s1e3mg3pk7e4eftt3vm3ra4j9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioFlutter',
  );
}
